/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package finalproject;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author ACER
 */
public class keuangan extends javax.swing.JFrame {

    PreparedStatement pst = null;
    ResultSet rs = null;

    /**
     * Creates new form keuangan
     */
    public keuangan() {
        initComponents();
        fetchData();
    }

    public ArrayList<KeuanganList> keuanganList() {
        ArrayList<KeuanganList> keuanganList = new ArrayList<>();
        try {//SELECT REPLACE(worker.isAcc,'1','Diterima') from worker
            Connection con = koneksi.getKoneksi();
            String sql = "SELECT * FROM `keuangan`";
            pst = con.prepareStatement(sql);
            rs = pst.executeQuery();
            KeuanganList keuangan;
            while (rs.next()) {
                keuangan = new KeuanganList(rs.getInt("id_keuangan"), rs.getInt("pemasukan"), rs.getInt("pengeluaran"));
                keuanganList.add(keuangan);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        }
        return keuanganList;
    }

    private void fetchData() {
        ArrayList<KeuanganList> list = keuanganList();
        DefaultTableModel model = (DefaultTableModel) dataKeuangan.getModel();
        Object[] row = new Object[4];
        for (int i = 0; i < list.size(); i++) {

            row[2] = list.get(i).getId_keuangan();
            row[1] = list.get(i).getPemasukan();
            row[0] = list.get(i).getPengeluaran();

            model.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        pemasukanTxt = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        pengeluaranTxt = new javax.swing.JTextField();
        tambahBarangTxt = new javax.swing.JButton();
        resetBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        dataKeuangan = new javax.swing.JTable();
        hapusTxt = new javax.swing.JButton();
        editTxt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 153, 153));

        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Kembali");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jLabel1.setForeground(new java.awt.Color(0, 0, 0));
        jLabel1.setText("Pemasukan :");

        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setText("Pengeluaran :");

        tambahBarangTxt.setForeground(new java.awt.Color(0, 0, 0));
        tambahBarangTxt.setText("Tambah");
        tambahBarangTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahBarangTxtActionPerformed(evt);
            }
        });

        resetBtn.setForeground(new java.awt.Color(0, 0, 0));
        resetBtn.setText("Reset");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(resetBtn)
                        .addGap(69, 69, 69)
                        .addComponent(tambahBarangTxt))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton3)
                                .addGap(79, 79, 79))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel1))
                                .addGap(36, 36, 36)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pemasukanTxt, javax.swing.GroupLayout.DEFAULT_SIZE, 159, Short.MAX_VALUE)
                            .addComponent(pengeluaranTxt))))
                .addGap(0, 46, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(pemasukanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pengeluaranTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(resetBtn)
                    .addComponent(tambahBarangTxt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3))
        );

        jLabel5.setFont(new java.awt.Font("sansserif", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 0, 0));
        jLabel5.setText("Data Keuangan");

        dataKeuangan.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id keuangan", "Pemasukan", "Pengeluaran"
            }
        ));
        dataKeuangan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dataKeuanganMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dataKeuangan);

        hapusTxt.setForeground(new java.awt.Color(0, 0, 0));
        hapusTxt.setText("Hapus");
        hapusTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusTxtActionPerformed(evt);
            }
        });

        editTxt.setForeground(new java.awt.Color(0, 0, 0));
        editTxt.setText("Edit");
        editTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editTxtActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 489, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(editTxt)
                                .addGap(70, 70, 70)
                                .addComponent(hapusTxt)
                                .addGap(40, 40, 40)))
                        .addGap(0, 145, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel5)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(312, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hapusTxt)
                    .addComponent(editTxt))
                .addGap(105, 105, 105))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        menu men = new menu();
        men.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void editTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editTxtActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = koneksi.getKoneksi();
            int row = dataKeuangan.getSelectedRow();
            String value = (dataKeuangan.getModel().getValueAt(row, 0).toString());
            String sql = "UPDATE keuangan SET pengeluaran =? , pemasukan =?  WHERE id_keuangan=" + value;
            if (pemasukanTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pemasukan tidak boleh kosong");
            } else if (pengeluaranTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pengeluaran tidak boleh kosong");
            } else {
                pst = con.prepareStatement(sql);
                pst.setString(1, pemasukanTxt.getText());
                pst.setString(2, pengeluaranTxt.getText());

                pst.executeUpdate();

                DefaultTableModel model = (DefaultTableModel) dataKeuangan.getModel();
                model.setRowCount(0);
                fetchData();
                pemasukanTxt.setText("");
                pengeluaranTxt.setText("");
                JOptionPane.showMessageDialog(null, "Update Selesai");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e.getMessage());
        }
    }//GEN-LAST:event_editTxtActionPerformed

    private void tambahBarangTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahBarangTxtActionPerformed
        // TODO add your handling code here:
        try {

            Connection con = koneksi.getKoneksi();
            //query insert data ke dalam database mysql
            pst = con.prepareStatement("INSERT INTO keuangan (pemasukan, pengeluaran) VALUES(?,?)");
            //validasi ketika textField kosong

            if (pemasukanTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pemasukan tidak boleh kosong");
            } else if (pengeluaranTxt.getText().isEmpty()) {
                JOptionPane.showMessageDialog(this, "Pengeluaran tidak boleh kosong");
            } else {
                //digunakan untuk memasukkan data ke masing2 variabel textfield seperti namaTxt, dll

                //misal bingung pst sama rs bisa diliat di variabel diatas
                pst.setString(1, pemasukanTxt.getText());
                pst.setString(2, pengeluaranTxt.getText());
                pst.executeUpdate();

                //setelah nginput data kasih ini biar textfieldnya kosong lagi
                pemasukanTxt.setText("");
                pengeluaranTxt.setText("");

                //setelah daftar muncul pop up dafatar berhasil dan akan tampil frame baru
                JOptionPane.showMessageDialog(null, "Pemasukan dan Pengeluaran berhasil ditambah");
                this.dispose();
                keuangan dashboard = new keuangan();
                dashboard.setVisible(true);

            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error " + e.getMessage());

        }
    }//GEN-LAST:event_tambahBarangTxtActionPerformed

    private void dataKeuanganMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dataKeuanganMouseClicked
        // TODO add your handling code here:
        int i = dataKeuangan.getSelectedRow();
        TableModel model = dataKeuangan.getModel();
        pemasukanTxt.setText(model.getValueAt(i, 1).toString());
        pengeluaranTxt.setText(model.getValueAt(i, 2).toString());

    }//GEN-LAST:event_dataKeuanganMouseClicked

    private void hapusTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusTxtActionPerformed
        // TODO add your handling code here:
        try {
            int pilihan = JOptionPane.showConfirmDialog(this, " Apakah anda yakin akan menghapus data ini ?", "Konfirmasi", JOptionPane.WARNING_MESSAGE);
            if (pilihan == JOptionPane.YES_OPTION) {
                Connection con = koneksi.getKoneksi();
                int row = dataKeuangan.getSelectedRow();
                String value = (dataKeuangan.getModel().getValueAt(row, 0).toString());
                String sql = "DELETE FROM keuangan WHERE id_keuangan=" + value;
                pst = con.prepareStatement(sql);
                pst.executeUpdate();
                pemasukanTxt.setText("");
                pengeluaranTxt.setText("");
                DefaultTableModel model = (DefaultTableModel) dataKeuangan.getModel();
                model.setRowCount(0);
                fetchData();
                JOptionPane.showMessageDialog(rootPane, "Data Dihapus");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Pilih Baris Dulu");
        }
    }//GEN-LAST:event_hapusTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(keuangan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new keuangan().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable dataKeuangan;
    private javax.swing.JButton editTxt;
    private javax.swing.JButton hapusTxt;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField pemasukanTxt;
    private javax.swing.JTextField pengeluaranTxt;
    private javax.swing.JButton resetBtn;
    private javax.swing.JButton tambahBarangTxt;
    // End of variables declaration//GEN-END:variables
}
